### PR TITLE
Completed Shortern Commit Messages

### PR DESCRIPTION
**Pull request by AlexErling**
## Summary

Added Line Ellipsis so it will shorten the message if it goes over 1 line. Additionally, made the date slightly opaque. 

Didn't mean to delete space in index.js. Just wanted to see what it would look like if it showed, for example, Alex Erling's Latest Github Activity, but I changed it back.

### CODE REVIEW

**Comment by jangerhard** [comment]
Nice! It would be great if this could be split into two pull requests; one for each issue it solves. Once we get Jest-testing up and running it would also be great if you could include some tests. We should have it up fairly soon, and testing would be done automatically through circleCi, but as of now we have to manually test.

**Comment by jangerhard** [comment]
I've taken a look at the commit so far, and while I like the look of the greyed out date, the component could use some work. Are you developing in a local environment where you can see your changes? 

This is what it looked like when I loaded up the changes:
image

For now, try to make some changes and add a commit on top of this one, but next time we'll hopefully have some Jest-testing in place, and keep it to one pull request per issue.

**Comment by jangerhard** [comment]
I took the liberty of creating a [new branch](https://github.com/jangerhard/react-github-showcase/commit/b84b3ae363bd30d6827c342fab1c6b75835d0307) based on your commit. Take a look and make some adjustments. It looked like react-lines-ellipsis couldn't keep the text to one line correctly so I did not include it. Maybe you can in a future commit after some tests have been added.

**Comment by AlexErling** [comment]
Okay, I will look into it and see if I can make adjustments. Ideally, you would like the date, to appear on the same line as the commit? Also, I'll have to see if I can use your same container so I will see exactly what you will be seeing. I guess I can keep working on this unless you have something else you might suggest I work on. Do you still want me to split off into two separate pull requests for the other thing added?

**Comment by jangerhard** [comment]
Perfect, Alex, yes one line would be great, but if you have any creative inputs, we are keen on listening! 

You could even provide a screenshot of what you are seeing. I'm considering doing different themes as examples to see how the component reacts.

**Comment by AlexErling** [comment]
reactapp

So I don't know the best way to go about this. But as shown in the photo, I think it could look good if the commit id was in bold, the message was displayed (I used this line to code to get it on one line, although I don't know if it will hold up on all the different themes though.
```
<span>{((message).length > 40) ?  (((message).substring(0,37)) + '...') : message } </span>
```

Another thing I've noticed is that when you load the component for the first time the picture is super streched out, so it might look cleaner if it's compressed of the beginning. 

Lastly, another idea I thought might look clear is instead of having the name under the photo, it could say for example "Alex Erling's Github Acitivity". And maybe come with a basic border to start.

**Comment by jangerhard** [comment]
Yeah, I like that look! See if it holds up when resizing the window; we'd want the component to be responsive. It's weird that your photo doesn't scale correctly. Have you tried putting the component in a div with some padding?

**Comment by AlexErling** [comment]
Yeah, I will look into seeing if I can make it more responsive, cause it is not currently. I will try putting it in a div with padding. And I'll figure out if I can make the photo scale correctly.

**Comment by jangerhard** [comment]
Perfect, Alex. See if a Div helps the situation. We'll be adding some automated tests soon, so we'll let you know when it's time to write some tests as well.

**Comment by AlexErling** [comment]
So I've made some changes and it seems to be holding up when I move the page. Is there a way I can show you what I've done so far without sending a pull request so you can let me know what you like. What's the best way to go about this?

**Comment by jangerhard** [comment]
Send some screenshots :)

**Comment by AlexErling** [comment]
Here what it looks like when I move the screen around. Still get's cramped when you compress the page too much, so I'll have to figure out the best css options for that, or if you have any ideas there.
photo1
photo2
photo3

**Comment by jangerhard** [comment]
I've been toying with the idea of having a media query just move the ProfileInfo up top, so that the repositories have a little bit more air to breathe. I'll have another look this week hopefully.

**Comment by AlexErling** [comment]
Okay, should I send a pull request or do anything in the meantime then?

**Comment by jangerhard** [comment]
You can keep tweaking this branch if you'd like! Hopefully we'll have merged the jest-testing branch by the end of the day, so we can start writing tests.

**Comment by jangerhard** [comment]
Jest testing have been added, so it would be great if some tests can be added :+1: This pull request can be focused on shortening the message, so don't worry about other enhancements in this one. When you fix the test and merge conflicts we can pull the request into master.

**Comment by AlexErling** [comment]
Okay, so I'll remove the CSS changes for now and only keep shortening the message. I haven't used Jest for testing before but I'll look into it.

**Comment by AlexErling** [comment]
Seeming how I've made some random change, I think I'm going to re-fork your repo again and start over and send in the pull requests with some tests added.

**Comment by jangerhard** [comment]
Sounds good, Alex! It's definitely an idea to keep the branches simple. Looking forward to merging the request!

**Comment by AlexErling** [comment]
Any other features that I might be able to take on?

**Pull request closed without merging**
